spring:
  application:
    name: third-part-index-data-project
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

# Dubbo Configuration
dubbo:
  application:
    name: ${spring.application.name}
  protocol:
    name: tri
    port: 20883
  registry:
    address: nacos://localhost:8848
  scan:
    base-packages: cn.how2j.trend.service.impl
