spring:
  application:
    name: third-part-index-data-project
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

# Dubbo Configuration
dubbo:
  application:
    name: ${spring.application.name}
    qos-enable: false
  protocol:
    name: tri
    port: 20883
    threads: 200
    queues: 0
    iothreads: 4
  registry:
    address: nacos://localhost:8848
    group: DUBBO_DEFAULT_GROUP
  provider:
    timeout: 30000
    retries: 0
    delay: -1
    loadbalance: roundrobin
  consumer:
    timeout: 30000
    retries: 0
    check: false
    loadbalance: roundrobin
  metadata-report:
    address: nacos://localhost:8848
    group: DUBBO_METADATA
  scan:
    base-packages: cn.how2j.trend.service.impl
