spring:
  application:
    name: index-codes-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  zipkin:
    base-url: http://localhost:9411

# Dubbo Configuration
dubbo:
  application:
    name: ${spring.application.name}
  protocol:
    name: tri
    port: 20881
  registry:
    address: nacos://localhost:8848
  scan:
    base-packages: cn.how2j.trend.service.impl
